from __future__ import annotations

import base64
import io
import textwrap
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "dashboard_standalone.py"


def iter_embedded_files() -> list[Path]:
    files: list[Path] = [
        ROOT / "dashboard_app.py",
        ROOT / "utils" / "__init__.py",
        ROOT / "utils" / "runtime_paths.py",
        ROOT / "utils" / "db.py",
        ROOT / "utils" / "operator_surface.py",
        ROOT / "utils" / "command_catalog.py",
        ROOT / "utils" / "command_descriptions.py",
        ROOT / "utils" / "helpers.py",
    ]
    files.extend(sorted((ROOT / "templates").glob("*.html")))
    files.extend(sorted((ROOT / "docs").glob("*.md")))
    files.extend(sorted((ROOT / "docs" / "ai_library").glob("*.md")))
    files.extend(sorted((ROOT / "cogs").glob("*.py")))
    return files


def build_payload(files: list[Path]) -> str:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in files:
            archive.write(path, path.relative_to(ROOT).as_posix())
    return base64.b64encode(buffer.getvalue()).decode("ascii")


def render_script(payload_b64: str, file_count: int) -> str:
    wrapped_payload = "\n".join(textwrap.wrap(payload_b64, width=88))
    return f'''#!/usr/bin/env python3
"""
Standalone raw Python entrypoint for the Loki dashboard.

Generated by `python scripts/build_dashboard_raw.py`.
Embedded files: {file_count}

This script unpacks the dashboard source, templates, docs, and command metadata inputs
into a temporary workspace, then runs the Flask dashboard while keeping `.env`, logs,
and `data/bot.db` next to this file.
"""

from __future__ import annotations

import atexit
import base64
import io
import os
import shutil
import sys
import tempfile
import zipfile
from pathlib import Path


PAYLOAD_B64 = """
{wrapped_payload}
"""


def extract_workspace() -> Path:
    workspace = Path(tempfile.mkdtemp(prefix="loki-dashboard-"))
    archive_bytes = base64.b64decode(PAYLOAD_B64.encode("ascii"))
    with zipfile.ZipFile(io.BytesIO(archive_bytes)) as archive:
        archive.extractall(workspace)
    return workspace


def configure_environment(workspace: Path) -> Path:
    app_root = Path(__file__).resolve().parent
    os.environ.setdefault("LOKI_APP_ROOT", str(app_root))
    os.environ.setdefault("LOKI_DB_PATH", str(app_root / "data" / "bot.db"))
    os.environ.setdefault("LOKI_ENV_PATH", str(app_root / ".env"))
    os.environ.setdefault("LOKI_RUNTIME_LOG_PATH", str(app_root / "desktop_runtime.log"))
    os.environ.setdefault("LOKI_COMMAND_ROOT", str(workspace))
    os.environ.setdefault("LOKI_DOCS_PATH", str(workspace / "docs"))
    os.environ.setdefault("LOKI_AI_DOCS_PATH", str(workspace / "docs" / "ai_library"))
    return app_root


def main() -> int:
    workspace = extract_workspace()
    atexit.register(lambda: shutil.rmtree(workspace, ignore_errors=True))
    app_root = configure_environment(workspace)
    sys.path.insert(0, str(workspace))

    import dashboard_app as dashboard_module

    host = os.getenv("DASHBOARD_HOST", "127.0.0.1")
    port = int(os.getenv("DASHBOARD_PORT", "5000"))
    debug = os.getenv("DASHBOARD_DEBUG", "false").lower() == "true"

    try:
        with dashboard_module.app.app_context():
            dashboard_module._ensure_streams_table()
    except Exception as exc:
        print(f"WARN: stream table bootstrap: {{exc}}")

    print(f"Dashboard runtime extracted to {{workspace}}")
    print(f"Dashboard app root is {{app_root}}")
    print(f"Dashboard running on http://{{host}}:{{port}}")
    dashboard_module.app.run(host=host, port=port, debug=debug)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def main() -> int:
    files = iter_embedded_files()
    payload = build_payload(files)
    OUTPUT.write_text(render_script(payload, len(files)), encoding="utf-8")
    print(f"Wrote {OUTPUT} with {len(files)} embedded files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
